namespace: pycrest

image:
  repository: chillmadiguys/emi-service
  tag: v1.1.0
  pullPolicy: Always

replicaCount: 1
minReadySeconds: 15

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 70
  memoryThreshold: 85

serviceAccount:
  name: emi-service-sa

configMapName: pycrest-global-config
secretName: pycrest-global-secret